baseURL = "https://shakmr.github.io/"
languageCode = 'es-es'
title = 'A poc a poc i amb bona lletra'
theme = "beautifulhugo"
defaultContentLanguage = "es"

[Params]
  subtitle = "My world of words"
  mainSections = ["posts"]
  favicon = "img/favicon.png"
  logo = "img/blogo/logo-opti.png"
  dateFormat = "02 Jan 2006"

[menu]
  [[menu.main]]
    name = "Acerca de"
    url = "/about"
    weight = 2
